## Reading JSON File

In [158]:
import pandas as pd

df=pd.read_json("C:/Users/harish/Downloads/1MB.json")

print(df)

                name language                id  \
0      Adeel Solangi   Sindhi  V59OF92YF627HFY0
1      Afzal Ghaffar   Sindhi  ENTOCR13RSCLZ6KU
2      Aamir Solangi   Sindhi  IAKPO3R4761JDRVG
3      Abla Dilmurat   Uyghur  5ZVOEPMJUI4MB4EN
4           Adil Eli   Uyghur  6VTI8X6LL0MMPJCC
...              ...      ...               ...
3163   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP
3164    Rohini Vasav    Hindi  UEFML43TCGS04KWM
3165    Sunil Kapoor    Hindi  VY2A0APGVHK5NAW2
3166  Zamokuhle Zulu  isiZulu  XU7BX2F8M5PVZ1EF
3167   Bhupesh Menon    Hindi  0CEPNRDV98KT3ORP

                                                    bio  version
0     Donec lobortis eleifend condimentum. Cras dict...     6.10
1     Aliquam sollicitudin ante ligula, eget malesua...     1.88
2     Vestibulum pharetra libero et velit gravida eu...     7.27
3     Donec lobortis eleifend condimentum. Morbi ac ...     2.53
4     Vivamus id faucibus velit, id posuere leo. Mor...     6.49
...                                                 ...      ...
3163  Maecenas tempus neque ut porttitor malesuada. ...     2.69
3164  Ut accumsan, est vel fringilla varius, purus a...     9.30
3165  Proin tempus eu risus nec mattis. Ut dictum, l...     8.04
3166  Etiam congue dignissim volutpat. Phasellus tin...     8.39
3167  Maecenas tempus neque ut porttitor malesuada. ...     2.69

[3168 rows x 5 columns]

## Reading Excel File

In [78]:
df1=pd.read_excel("C:/Users/harish/Downloads/Supermarket-Sales-Sample-Data.xlsx")
df1.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
67,NaN,1061,2024-01-31 00:00:00,Daniel Hernandez,2024-02-02 00:00:00,149.99,1,14.999,164.989
68,NaN,1062,2024-01-31 00:00:00,Jennifer Davis,2024-02-04 00:00:00,69.99,2,13.998,153.978
69,NaN,1063,2024-02-01 00:00:00,Michael Martinez,2024-02-02 00:00:00,39.99,3,11.997,131.967
70,NaN,1064,2024-02-01 00:00:00,Jessica Wilson,2024-02-05 00:00:00,199.99,1,19.999,219.989
71,NaN,1065,2024-02-01 00:00:00,David Rodriguez,2024-02-03 00:00:00,29.99,5,14.995,164.945
72,NaN,1066,2024-02-02 00:00:00,Sarah Gonzalez,2024-02-06 00:00:00,79.99,2,15.998,175.978
73,NaN,1067,2024-02-03 00:00:00,Matthew Smith,2024-02-06 00:00:00,49.99,3,14.997,164.967
74,NaN,1068,2024-02-04 00:00:00,Emily Johnson,2024-02-05 00:00:00,129.99,1,12.999,142.989
75,NaN,1069,2024-02-04 00:00:00,Daniel Brown,2024-02-08 00:00:00,19.99,4,7.996,87.956
76,NaN,1070,2024-02-04 00:00:00,Jennifer Hernandez,2024-02-07 00:00:00,149.99,1,14.999,164.989

## Reading CSV File

In [79]:
df2=pd.read_csv("C:/Users/harish/Downloads/deliveries.csv/deliveries.csv")
df2.head(10)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,0,4,NaN,0,NaN,NaN,NaN

### Checking Missing Values in Dataset

In [80]:
#isnull
#used to identify missing values
print(df.isnull())

       name  language     id    bio  version
0     False     False  False  False    False
1     False     False  False  False    False
2     False     False  False  False    False
3     False     False  False  False    False
4     False     False  False  False    False
...     ...       ...    ...    ...      ...
3163  False     False  False  False    False
3164  False     False  False  False    False
3165  False     False  False  False    False
3166  False     False  False  False    False
3167  False     False  False  False    False

[3168 rows x 5 columns]

In [81]:
#count missing values for all fields
df.isnull().sum()

name        0
language    0
id          0
bio         0
version     0
dtype: int64

In [82]:
#Find Rows Having Missing id
df[df['id'].isnull()]

Empty DataFrame
Columns: [name, language, id, bio, version]
Index: []

In [83]:
#count missing values for all fields in df1
df1.isnull().sum()

Unnamed: 0    77
Unnamed: 1     4
Unnamed: 2     6
Unnamed: 3     6
Unnamed: 4     6
Unnamed: 5     6
Unnamed: 6     6
Unnamed: 7     5
Unnamed: 8     5
dtype: int64

In [84]:
#Find Rows Having Missing id
df1[df1['Unnamed: 5'].isnull()]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Supermarket Sales Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tax,0.1
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
print(df1['Unnamed: 5'].dtype)

object

In [86]:
#Converting Object to Numeric Data
df1['Unnamed: 5'] = pd.to_numeric(df1['Unnamed: 5'], errors='coerce')

In [87]:
# Filling Embarked with Most Frequent Value or Mean Value
meanval=df1['Unnamed: 5'].mean()
df1['Unnamed: 5']=df1['Unnamed: 5'].fillna(meanval)

In [88]:
# Filling Embarked with Most Frequent Value
# by using mode() means the most frequently occuring value in a column

mode_embarked=df1['Unnamed: 5'].mode()[0]

df1['Unnamed: 5']=df1['Unnamed: 5'].fillna(mode_embarked)

In [89]:
#dropna()
#Remove Missing Data
#Remove Column
df1.dropna(axis=1)

    Unnamed: 5
0    84.418571
1    84.418571
2    84.418571
3    84.418571
4    84.418571
..         ...
72   79.990000
73   49.990000
74  129.990000
75   19.990000
76  149.990000

[77 rows x 1 columns]

In [90]:
df3=pd.read_csv("C:/Users/harish/Downloads/customers-1000.csv")

In [91]:
df3.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
5,6,8aaa5d0CE9ee311,Marissa,Gamble,Cherry and Sons,Webertown,Sudan,001-645-334-5514x0786,(751)980-3163,katieallison@leonard.com,2021-11-17,http://www.kaufman.org/
6,7,73B22Ac8A43DD1A,Julie,Cooley,"Yu, Norman and Sharp",West Sandra,Japan,+1-675-243-7422x9177,(703)337-5903,priscilla88@stephens.info,2022-03-26,http://www.sexton-chang.com/
7,8,DC94CCd993D311b,Lauren,Villa,"French, Travis and Hensley",New Yolanda,Fiji,081.226.1797x647,186.540.9690x605,colehumphrey@austin-caldwell.com,2020-08-14,https://www.kerr.com/
8,9,9Ba746Cb790FED9,Emily,Bryant,"Moon, Strickland and Combs",East Normanchester,Seychelles,430-401-5228x35091,115-835-3840,buckyvonne@church-lutz.com,2020-12-30,http://grimes.com/
9,10,aAa1EDfaA70DA0c,Marie,Estrada,May Inc,Welchton,United Arab Emirates,001-648-790-9244,973-767-3611,christie44@mckenzie.biz,2020-09-03,https://www.salinas.net/

In [92]:
#finding null value
print(df3.isnull())

     Index  Customer Id  First Name  Last Name  Company   City  Country  \
0    False        False       False      False    False  False    False
1    False        False       False      False    False  False    False
2    False        False       False      False    False  False    False
3    False        False       False      False    False  False    False
4    False        False       False      False    False  False    False
..     ...          ...         ...        ...      ...    ...      ...
995  False        False       False      False    False  False    False
996  False        False       False      False    False  False    False
997  False        False       False      False    False  False    False
998  False        False       False      False    False  False    False
999  False        False       False      False    False  False    False

     Phone 1  Phone 2  Email  Subscription Date  Website
0      False    False  False              False    False
1      False    False  False              False    False
2      False    False  False              False    False
3      False    False  False              False    False
4      False    False  False              False    False
..       ...      ...    ...                ...      ...
995    False    False  False              False    False
996    False    False  False              False    False
997    False    False  False              False    False
998    False    False  False              False    False
999    False    False  False              False    False

[1000 rows x 12 columns]

In [93]:
# counting null value
print(df3.isnull().sum())

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [95]:
#Change mu index to customer id
df3=pd.read_csv("C:/Users/harish/Downloads/customers-1000.csv",index_col='Customer Id')
print(df3)

                 Index First Name Last Name                      Company  \
Customer Id
dE014d010c7ab0c      1     Andrew   Goodman                Stewart-Flynn
2B54172c8b65eC3      2      Alvin      Lane  Terry, Proctor and Lawrence
d794Dd48988d2ac      3      Jenna   Harding                 Bailey Group
3b3Aa4aCc68f3Be      4   Fernando      Ford                 Moss-Maxwell
D60df62ad2ae41E      5       Kara     Woods              Mccarthy-Kelley
...                ...        ...       ...                          ...
FbcCaF483aFaFAE    996      Diana    Monroe                  Bass-Wilson
979c4D58Ae9a9cc    997      Jerry   Morales                   Pratt-King
D0DcF6a4BcefCc8    998     Tracie     Floyd     Holt, Wilson and Shields
90EE9CbbDa374E9    999       Paul    Barnes     Brown, Oliver and Haynes
51732B5b2328015   1000    Dominic     Duran                   Durham LLC

                                 City  \
Customer Id
dE014d010c7ab0c           Rowlandberg
2B54172c8b65eC3              Bethside
d794Dd48988d2ac          Moniquemouth
3b3Aa4aCc68f3Be            Leeborough
D60df62ad2ae41E      Port Jacksonland
...                               ...
FbcCaF483aFaFAE     Lake Jacksonmouth
979c4D58Ae9a9cc  South Dominiquemouth
D0DcF6a4BcefCc8       East Chloeshire
90EE9CbbDa374E9           South Shane
51732B5b2328015            East Wendy

                                                           Country  \
Customer Id
dE014d010c7ab0c                                              Macao
2B54172c8b65eC3                                   Papua New Guinea
d794Dd48988d2ac                                              China
3b3Aa4aCc68f3Be                                              Macao
D60df62ad2ae41E                                              Nepal
...                                                            ...
FbcCaF483aFaFAE                                          Guatemala
979c4D58Ae9a9cc                                            Georgia
D0DcF6a4BcefCc8                                    Solomon Islands
90EE9CbbDa374E9                                            Finland
51732B5b2328015  British Indian Ocean Territory (Chagos Archipe...

                               Phone 1                Phone 2  \
Customer Id
dE014d010c7ab0c      846-790-4623x4715    (422)787-2331x71127
2B54172c8b65eC3     124-597-8652x05682      321.441.0588x6218
d794Dd48988d2ac     (335)987-3085x3780       001-680-204-8312
3b3Aa4aCc68f3Be          (047)752-3122      048.779.5035x9122
D60df62ad2ae41E  +1-360-693-4419x19272           163-627-2565
...                                ...                    ...
FbcCaF483aFaFAE  +1-171-715-9766x54993    (489)413-7296x32807
979c4D58Ae9a9cc       132.253.8501x097  +1-301-292-8363x80270
D0DcF6a4BcefCc8             1193982387          (482)926-8966
90EE9CbbDa374E9   +1-537-466-3245x3699           791-835-9075
51732B5b2328015        +1-278-758-4331       814-860-0941x057

                                         Email Subscription Date  \
Customer Id
dE014d010c7ab0c  marieyates@gomez-spencer.info        2021-07-26
2B54172c8b65eC3          alexandra86@mccoy.com        2021-06-24
d794Dd48988d2ac        justincurtis@pierce.org        2020-04-05
3b3Aa4aCc68f3Be            adeleon@hubbard.org        2020-11-29
D60df62ad2ae41E          jesus90@roberson.info        2022-04-22
...                                        ...               ...
FbcCaF483aFaFAE     cassidymercado@bonilla.com        2022-01-09
979c4D58Ae9a9cc        gavin13@logan-downs.com        2021-08-21
D0DcF6a4BcefCc8         lowehailey@oconnor.org        2020-04-22
90EE9CbbDa374E9   hodgeseddie@hardin-wells.com        2021-03-12
51732B5b2328015         owarner@velasquez.info        2021-12-09

                                      Website
Customer Id
dE014d010c7ab0c          http://www.shea.biz/
2B54172c8b65eC3     http://www.pena-cole.com/
d794Dd48988d2ac   http://www.booth-reese.biz/
3b3Aa4aCc68f3Be        http://www.hebert.com/
D60df62ad2ae41E           http://merritt.com/
...                                       ...
FbcCaF483aFaFAE            http://castro.net/
979c4D58Ae9a9cc       https://www.braun.info/
D0DcF6a4BcefCc8  http://www.zavala-rubio.com/
90EE9CbbDa374E9  https://stone-randolph.info/
51732B5b2328015           http://www.cox.com/

[1000 rows x 11 columns]

In [94]:
#you need specific row and column
print(df.iloc[0:5,1:3])

  language                id
0   Sindhi  V59OF92YF627HFY0
1   Sindhi  ENTOCR13RSCLZ6KU
2   Sindhi  IAKPO3R4761JDRVG
3   Uyghur  5ZVOEPMJUI4MB4EN
4   Uyghur  6VTI8X6LL0MMPJCC

In [96]:
#Accessing Specific Columns for Particular index
print(df3.loc['D0DcF6a4BcefCc8',['First Name','Company']])

First Name                      Tracie
Company       Holt, Wilson and Shields
Name: D0DcF6a4BcefCc8, dtype: object

In [97]:
#Range from this to that
print(df3.loc['FbcCaF483aFaFAE':'51732B5b2328015',['First Name','Company']])

                First Name                   Company
Customer Id
FbcCaF483aFaFAE      Diana               Bass-Wilson
979c4D58Ae9a9cc      Jerry                Pratt-King
D0DcF6a4BcefCc8     Tracie  Holt, Wilson and Shields
90EE9CbbDa374E9       Paul  Brown, Oliver and Haynes
51732B5b2328015    Dominic                Durham LLC

In [103]:
df4=pd.read_csv("C:/Users/harish/Downloads/Titanic-Dataset.csv")

In [105]:
df4.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [100]:
df4.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [106]:
df4['Age'] = df4['Age'].fillna(df4['Age'].median())

In [109]:
df4['Embarked'] = df4['Embarked'].fillna(df4['Embarked'].mode()[0])

In [111]:
df4['Cabin'] = df4['Cabin'].fillna('Unknown')

In [112]:
df4.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [115]:
#Agg()
print(df4.groupby('Pclass').agg({
    'Age':['mean','min','max'],
    'Fare':['min','max']
}))

              Age             Fare
             mean   min   max  min       max
Pclass
1       36.812130  0.92  80.0  0.0  512.3292
2       29.765380  0.67  70.0  0.0   73.5000
3       25.932627  0.42  74.0  0.0   69.5500

In [119]:
#interpolate()
#Estimate missing Values.

sample=pd.DataFrame({
    'Age':[20,25,None,35,40]
})

sample['Age']=sample['Age'].interpolate()

print(sample)

    Age
0  20.0
1  25.0
2  30.0
3  35.0
4  40.0

------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------

In [121]:
import pandas as pd

students=pd.read_excel("C:/Users/harish/Downloads/Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="students")

marks=pd.read_excel("C:/Users/harish/Downloads/Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="marks")

contact=pd.read_excel("C:/Users/harish/Downloads/Merge_Join_Concat_Dataset_50_Records.xlsx",sheet_name="contact")

In [124]:
# 1. INNER MERGE

#Returns only Matching Student_IDs from both DataFrames.

inner_df=pd.merge(
    students,
    marks,
    on="Student_ID",
    how="inner"
)

print(inner_df.head())
print(inner_df.shape)

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60
(45, 5)

In [138]:
# 2.LEFT MERGE
left_df=pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

print(left_df.head())
print(left_df.shape)

#Even if marks are missing

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE   61.0    56.0
1        1002  Student_2         IT   62.0    57.0
2        1003  Student_3        ECE   63.0    58.0
3        1004  Student_4        EEE   64.0    59.0
4        1005  Student_5       MECH   65.0    60.0
(50, 5)

In [127]:
# 3.RIGHT MERGE
right_df=pd.merge(
    students,
    marks,
    on="Student_ID",
    how="right"
)

print(right_df.head())
print(right_df.shape)

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE     61      56
1        1002  Student_2         IT     62      57
2        1003  Student_3        ECE     63      58
3        1004  Student_4        EEE     64      59
4        1005  Student_5       MECH     65      60
(50, 5)

In [128]:
# 4. OUTER MERGE
# Keeps everything from both DataFrames.
outer_df=pd.merge(
    students,
    marks,
    on="Student_ID",
    how="outer"
)

print(outer_df.head())
print(outer_df.shape)

   Student_ID       Name Department  Maths  Python
0        1001  Student_1        CSE   61.0    56.0
1        1002  Student_2         IT   62.0    57.0
2        1003  Student_3        ECE   63.0    58.0
3        1004  Student_4        EEE   64.0    59.0
4        1005  Student_5       MECH   65.0    60.0
(55, 5)

In [131]:
# 5.

#Combine Students + Marks + Contact.

student_complete=pd.merge(
    students,
    marks,
    on="Student_ID",
    how="left"
)

student_complete=pd.merge(
    student_complete,
    contact,
    on="Student_ID",
    how="left"
)

print(student_complete.head())

   Student_ID       Name Department  Maths  Python                 Email
0        1001  Student_1        CSE   61.0    56.0  student1@college.edu
1        1002  Student_2         IT   62.0    57.0  student2@college.edu
2        1003  Student_3        ECE   63.0    58.0  student3@college.edu
3        1004  Student_4        EEE   64.0    59.0  student4@college.edu
4        1005  Student_5       MECH   65.0    60.0  student5@college.edu

In [135]:
# 6. CONCAT ROW-WISE

#Split Students into two parts.

part1=students.iloc[:25]
part2=students.iloc[25:]

combined_rows=pd.concat([part1,part2])

print(combined_rows.head())
print(combined_rows.shape)

   Student_ID       Name Department
0        1001  Student_1        CSE
1        1002  Student_2         IT
2        1003  Student_3        ECE
3        1004  Student_4        EEE
4        1005  Student_5       MECH
(50, 3)

In [136]:
# 7.CONCAT COLUMN-WISE

student_basic=students[['Student_ID','Name']]
student_marks=marks[['Python']]
combined_cols=pd.concat(
    [student_basic,student_marks],
    axis=1
)

print(combined_cols.head())
print(combined_cols.shape)

   Student_ID       Name  Python
0        1001  Student_1      56
1        1002  Student_2      57
2        1003  Student_3      58
3        1004  Student_4      59
4        1005  Student_5      60
(50, 3)

In [137]:
# 8. JOIN()

#join() works using indexes.

students_index=students.set_index("Student_ID")
contact_index=contact.set_index("Student_ID")

joined_df=students_index.join(contact_index)

print(joined_df.tail(10))

                  Name Department                  Email
Student_ID
1041        Student_41        CSE  student41@college.edu
1042        Student_42         IT  student42@college.edu
1043        Student_43        ECE  student43@college.edu
1044        Student_44        EEE  student44@college.edu
1045        Student_45       MECH  student45@college.edu
1046        Student_46        CSE  student46@college.edu
1047        Student_47         IT  student47@college.edu
1048        Student_48        ECE  student48@college.edu
1049        Student_49        EEE  student49@college.edu
1050        Student_50       MECH  student50@college.edu

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Pivot Table

Pivot Table is used to summarize and analyze data by grouping rows and applying aggregate functions such as sum, mean, count, max, min, etc.

In [141]:
# Step 1: Load Dataset

import pandas as pd

df5=pd.read_csv("C:/Users/harish/Downloads/people-10000.csv")

print(df5.head())

   Index          User Id First Name Last Name     Sex  \
0      1  5f10e9D33fC5f2b       Sara   Mcguire  Female
1      2  751cD1cbF77e005     Alisha    Hebert    Male
2      3  DcEFDB2D2e62bF9  Gwendolyn  Sheppard    Male
3      4  C88661E02EEDA9e   Kristine    Mccann  Female
4      5  fafF1aBDebaB2a6      Bobby   Pittman  Female

                         Email                  Phone Date of birth  \
0           tsharp@example.net     (971)643-6089x9160    1921-08-17
1   vincentgarrett@example.net  +1-114-355-1841x78347    1969-06-28
2  mercadojonathan@example.com             9017807728    1915-09-25
3        lindsay55@example.com  +1-607-333-9911x59088    1978-07-27
4    blevinsmorgan@example.com             3739847538    1989-11-17

                           Job Title
0              Editor, commissioning
1                 Broadcast engineer
2                   Industrial buyer
3              Multimedia specialist
4  Planning and development surveyor

In [142]:
# Step 2: Create Age Column
df5['Date of birth']=pd.to_datetime(df5['Date of birth'])

today=pd.Timestamp.today()

df5['Age']=(
    (today-df5['Date of birth']).dt.days//365
)

print(df5[['First Name','Sex','Age']].head())

  First Name     Sex  Age
0       Sara  Female  104
1     Alisha    Male   56
2  Gwendolyn    Male  110
3   Kristine  Female   47
4      Bobby  Female   36

--if cannot upload files directly in colab
* from google.colab import files

In [144]:
# 1. Basic Pivot Table

# Average age by gender.

pivot1=pd.pivot_table(
    df5,
    values='Age',
    index='Sex'
)

print(pivot1)

              Age
Sex
Female  60.725266
Male    61.034917

In [146]:
# 2.Pivot Table with aggfunc='mean'

pivot2=pd.pivot_table(
    df5,
    values='Age',
    index='Sex',
    aggfunc='mean'
)

print(pivot2)

              Age
Sex
Female  60.725266
Male    61.034917

In [149]:
# 3.Pivot Table with aggfunc='sum'

pivot3=pd.pivot_table(
    df5,
    values='Age',
    index='Sex',
    aggfunc='sum'
)

print(pivot3)

           Age
Sex
Female  308120
Male    300658

In [150]:
# 4.Pivot Table with aggfunc='count'

pivot4=pd.pivot_table(
    df5,
    values='Age',
    index='Sex',
    aggfunc='count'
)

print(pivot4)

         Age
Sex
Female  5074
Male    4926

In [151]:
#5. Multiple Aggregations.

pivot5=pd.pivot_table(
    df5,
    values='Age',
    index='Sex',
    aggfunc=['mean','max','min']
)

print(pivot5)

             mean  max min
              Age  Age Age
Sex
Female  60.725266  120   4
Male    61.034917  120   4

In [152]:
#6. Pivot Table with margins=True

# Adds overall average

pivot6=pd.pivot_table(
    df5,
    values='Age',
    index='Sex',
    aggfunc='mean',
    margins=True
)

print(pivot6)

              Age
Sex
Female  60.725266
Male    61.034917
All     60.877800

In [155]:
#7 .Group by Job Title and Gender

# Average age by Job Title and Gender.

pivot7=pd.pivot_table(
    df5,
    values='Age',
    index='Job Title',
    columns='Sex',
    aggfunc='mean'
)
print(pivot7)

Sex                                  Female       Male
Job Title
Academic librarian                75.333333  61.100000
Accommodation manager             68.000000  45.250000
Accountant, chartered             42.100000  68.800000
Accountant, chartered certified   57.428571  66.785714
Accountant, chartered management  66.888889  61.272727
...                                     ...        ...
Water quality scientist           56.375000  66.600000
Web designer                      71.444444  51.000000
Wellsite geologist                52.470588  72.636364
Writer                            69.750000  75.307692
Youth worker                      62.200000  72.500000

[639 rows x 2 columns]

In [156]:
# 8. 

# Count People by Job and Gender

pivot8=pd.pivot_table(
    df5,
    values='User Id',
    index='Job Title',
    columns='Sex',
    aggfunc='count',
    fill_value=0
)

print(pivot8)

#nan fill value with 0

Sex                               Female  Male
Job Title
Academic librarian                     3    10
Accommodation manager                  8     4
Accountant, chartered                 10     5
Accountant, chartered certified        7    14
Accountant, chartered management       9    11
...                                  ...   ...
Water quality scientist                8    10
Web designer                           9     5
Wellsite geologist                    17    11
Writer                                12    13
Youth worker                           5     4

[639 rows x 2 columns]

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [170]:
import pandas as pd
df6=pd.read_excel("C:/Users/harish/Downloads/Data_Cleaning_50Plus_Records.xlsx")
print(df6.head())

   Student ID Student Name   Department   Age   Salary               Email
0         101      student1          IT  20.0  23075.0  student1@gmail.com
1         102      student2         ECE  18.0  35929.0  student2@gmail.com
2         103      STUDENT3         EEE  22.0  29718.0  student3@gmail.com
3         104      student4        MECH  20.0  21009.0  student4@gmail.com
4         105     Student5          CSE  19.0  47113.0  student5@gmail.com

In [171]:
print(df6.columns)

Index(['Student ID', 'Student Name ', ' Department', 'Age', 'Salary', 'Email'], dtype='object')

In [172]:
# Rename Columns

df6.rename(columns={
    'Student ID':'Student_ID',
    'Student Name ':'Student_Name',
    ' Department':'Department'
},inplace=True)

print(df6.columns)

Index(['Student_ID', 'Student_Name', 'Department', 'Age', 'Salary', 'Email'], dtype='object')

In [174]:
#3. Changing Data Types
# Check Data Types:
print(df6.dtypes)

Student_ID        int64
Student_Name     object
Department       object
Age             float64
Salary          float64
Email            object
dtype: object

In [175]:
# Convert Student_ID to String

df6['Student_ID']=df6['Student_ID'].astype(str)

#Convert Age to Integer

#First handle missing values.

df6['Age']=df6['Age'].fillna(0)
df6['Age']=df6['Age'].astype(int)

#Check:

print(df6.dtypes)

Student_ID       object
Student_Name     object
Department       object
Age               int32
Salary          float64
Email            object
dtype: object

In [177]:
#4. Detecting Duplicate Records

#Find Duplicates

duplicates=df6.duplicated()
print(duplicates)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
dtype: bool